---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Shamalya D
  - Another author
thanks: "Code and data are available at: [https://github.com/RohanAlexander/starter_folder](https://github.com/RohanAlexander/starter_folder)."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

# Introduction

# Data

## Data Set Overview

add a summary statistics table here maybe?

## Variables

Mention any variables that were constructed here, as well

## High Level Data Cleaning 

## Summary Statistics

## Graphs for Imp. Variables (relationships)

## Measurement

Public support for political candidates is an essential part of understanding electoral dynamics for a variety of reasons. Public polls provide insights into the preferences and beliefs of certain groups of people, usually voters in specific states or districts, and sometimes to also correlate preferences to demographic information (race, age, neighbourhood, etc).

The results help inform policy decisions, help track the likely outcomes of elections, help government officials and candidates decide where to invest time, funds, and resources to get the desired results. Polling organizations aim to capture data by surveying a representative sample of voters, free from government intervention.

Polling organizations conduct these surveys through various methods. For our particular data set, the following methods have been used to gauge public sentiment:

-   App panel

-   Online panel

-   Email

-   Online ad

-   IVR (interactive voice response)

-   Live phone

-   Text

-   Text-to-web

-   Probability panel

-   Mail-to-phone

Each pollster chooses a method(s) based on what they find to be most convenient, efficient, and providing the best results. Moreover, there are some variables which affect the validity and reliability of the polling results, such as sample size, methodology, population type, etc. Larger samples generally lead to more reliable estimates of public opinion. Some methodologies might be considered more reliable due to certain factors. The pollsters also use different sampling methods (random, stratified, etc) which can affect the validity of the polling results as well.

After collecting the required data, the polling organizations transform these results into more easily comprehensible variables such as numeric grade, poll score, transparency score, and a percentage. These scores are calculated through an extensive process of calculating excess error and bias, adjusting for race difficulty, calculating predictive error and bias, calculating pollster transparency, and combining everything into one single ‘POLLSCORE’, while accounting for luck as well.

Variables such as pollster rating and transparency score help validate the reliability of the pollster and the polling results they publish.

Each entry in the dataset represents a glimpse of public opinion at a specific time and location, capturing measured support percentages alongside contextual variables such as pollster, methodology, and sample size. This extensive approach allows for an enhanced understanding of public support dynamics, facilitating informed analyses of electoral outcomes.

```{r}
library(arrow)
analysis_data <- read_parquet(here::here("data/02-analysis_data/analysis_data.parquet"))

head(analysis_data)
```
